# Generated by Django 5.2.4 on 2026-01-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='contextdata',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='ervisit',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='experiencefailureindicator',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='experiencefailureindicator',
            name='time_to_first_contact',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencefailureindicator',
            name='time_without_communication',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='satisfactionsignal',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
