# Generated by Django 5.2.9 on 2026-01-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextdata',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contextdata',
            name='er_section',
            field=models.CharField(choices=[('main', 'Main ER'), ('fasttrack', 'Fast Track'), ('trauma', 'Trauma Bay'), ('peds', 'Pediatrics')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ervisit',
            name='arrival_ts',
            field=models.DateTimeField(),
        ),
    ]
