# Generated by Django 5.2.4 on 2026-01-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_contextdata_date_alter_contextdata_er_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencefailureindicator',
            name='time_to_first_contact',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='experiencefailureindicator',
            name='time_without_communication',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
    ]
