# Generated by Django 5.2.4 on 2026-01-07 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_experiencefailureindicator_time_to_first_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencefailureindicator',
            name='comm_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failure_indicator', to='patients.communicationevent'),
        ),
        migrations.AlterField(
            model_name='experiencefailureindicator',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_report', to='patients.ervisit'),
        ),
    ]
