# Generated by Django 5.2.4 on 2026-01-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
