# Generated by Django 5.2.4 on 2026-01-04 17:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextData',
            fields=[
                ('context_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift', models.CharField(choices=[('day', 'Day (07:00 - 15:00)'), ('evening', 'Evening (15:00 - 23:00)'), ('night', 'Night (23:00 - 07:00)')], default='day', max_length=50)),
                ('staffing_level', models.CharField(choices=[('low', 'Low Staffing'), ('medium', 'Normal Staffing'), ('high', 'Full Staffing')], default='medium', max_length=50)),
                ('er_capacity_level', models.CharField(choices=[('under', 'Under Capacity'), ('at', 'At Capacity'), ('over', 'Over Capacity')], default='at', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('er_section', models.CharField(choices=[('Main', 'Main ER'), ('FastTrack', 'Fast Track'), ('Trauma', 'Trauma Bay'), ('Peds', 'Pediatrics')], max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'er_section'], name='patients_co_date_bc4d3f_idx')],
                'unique_together': {('date', 'shift', 'er_section')},
            },
        ),
        migrations.CreateModel(
            name='ERVisit',
            fields=[
                ('visit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arrival_ts', models.DateTimeField(auto_now_add=True)),
                ('triage_ts', models.DateTimeField(blank=True, null=True)),
                ('first_contact_ts', models.DateTimeField(blank=True, null=True)),
                ('disposition_ts', models.DateTimeField(blank=True, null=True)),
                ('triage_level', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('er_section', models.CharField(choices=[('main', 'Main ER'), ('fasttrack', 'Fast Track'), ('trauma', 'Trauma Bay'), ('peds', 'Pediatrics')], max_length=50)),
                ('disposition_type', models.CharField(blank=True, choices=[('admitted', 'Admitted to Hospital'), ('discharged', 'Discharged Home'), ('lwbs', 'Left Without Being Seen'), ('transferred', 'Transferred to Other Facility')], max_length=50, null=True)),
                ('length_of_stay', models.DurationField(blank=True, editable=False, null=True)),
                ('revisit_72h', models.BooleanField(default=False)),
                ('age_group', models.CharField(blank=True, choices=[('child', 'Child (0-12)'), ('teen', 'Teen (13-17)'), ('young_adult', 'Young Adult (18-34)'), ('adult', 'Adult (35-64)'), ('senior', 'Senior (65+)')], max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='er_visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('initial', 'Initial Contact'), ('delay_update', 'Delay/Wait Time Update'), ('clinical_update', 'Clinical/Results Update'), ('other', 'Other')], default='initial', max_length=50)),
                ('event_ts', models.DateTimeField(auto_now_add=True)),
                ('staff_role', models.CharField(choices=[('nurse', 'Nurse'), ('physician', 'Physician'), ('admin', 'Admin')], max_length=20)),
                ('initiated_by', models.CharField(choices=[('staff', 'Staff Proactive'), ('patient', 'Patient/Family Request')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='patients.ervisit')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceFailureIndicator',
            fields=[
                ('indicator_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lwbs', models.BooleanField(default=False)),
                ('time_to_first_contact', models.DurationField(blank=True, editable=False, null=True)),
                ('time_without_communication', models.DurationField(blank=True, editable=False, null=True)),
                ('revisit_reason', models.CharField(blank=True, choices=[('worsening', 'Symptoms Worsened'), ('new_issue', 'New Unrelated Issue'), ('planned', 'Planned Follow-up')], max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('comm_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failure_indicator', to='patients.communicationevent')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='failure_report', to='patients.ervisit')),
            ],
        ),
        migrations.CreateModel(
            name='SatisfactionSignal',
            fields=[
                ('feedback_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('waiting_score', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_score', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('respect_score', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='patients.ervisit')),
            ],
        ),
        migrations.AddIndex(
            model_name='ervisit',
            index=models.Index(fields=['er_section', 'triage_level'], name='patients_er_er_sect_b393cb_idx'),
        ),
        migrations.AddIndex(
            model_name='ervisit',
            index=models.Index(fields=['disposition_type'], name='patients_er_disposi_036780_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ervisit',
            unique_together={('patient', 'arrival_ts')},
        ),
        migrations.AddIndex(
            model_name='communicationevent',
            index=models.Index(fields=['visit', 'event_ts'], name='patients_co_visit_i_0a1505_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationevent',
            index=models.Index(fields=['event_type'], name='patients_co_event_t_e6a6ed_idx'),
        ),
        migrations.AddIndex(
            model_name='experiencefailureindicator',
            index=models.Index(fields=['lwbs'], name='patients_ex_lwbs_1d9496_idx'),
        ),
        migrations.AddIndex(
            model_name='experiencefailureindicator',
            index=models.Index(fields=['time_to_first_contact'], name='patients_ex_time_to_3b4dcb_idx'),
        ),
        migrations.AddIndex(
            model_name='satisfactionsignal',
            index=models.Index(fields=['overall_score', 'waiting_score'], name='patients_sa_overall_db1b44_idx'),
        ),
    ]
